### ISSUE TITLE
Cross-platfrom file watching support 

### ISSUE THREAD

**Issue by mre** [rabite0/hunter#12] opened 2019-04-08 15:42 UTC
On macOS, compilation currently fails with the following error message:

```rust
  Compiling hunter v1.0.1 (/Users/mendler/Code/upstream/hunter)
error[E0432]: unresolved import `notify::INotifyWatcher`
 --> src/fscache.rs:1:14
  |
1 | use notify::{INotifyWatcher, Watcher, DebouncedEvent, RecursiveMode};
  |              ^^^^^^^^^^^^^^ no `INotifyWatcher` in the root
```

That's because `inotifywatch` is Linux-specific.
I recommend https://github.com/passcod/notify for cross-platform filesystem notifications.

**Comment by rabite0** [comment] 2019-04-08 16:03
Is that the only blocking issue for OSX? Hard to say I guess.

Should be an easy fix, that's the library I'm actually already using, so this would be a small change. Will look into that. Thanks for reporting.

**Comment by mre** [comment] 2019-04-08 17:13
Yeah from what I can tell, it should be the only issue. The other crates either explicitly mention macOS support or they are platform-independent.

**Comment by dmilith** [comment] 2019-04-11 11:20
https://twitter.com/dmilith/status/1116298950066176001

**Comment by dmilith** [comment] 2019-04-11 11:26
To make a long story short - "inotify" (but also epoll) are Linux only "techno-logies", so using Linux only stuff will limit usability of the project on other platforms :)

**Comment by rabite0** [comment] 2019-04-11 12:07
Yeah, this also prevents it from working on BSD systems. Ironically it works nicely on Windows (with WSL)... 
The crate I use is already cross-platform, I just failed to use it that way, so this shouldn't take much work. Will fix this in the next few days.

**Comment by rabite0** [comment] 2019-04-11 12:23
Ok, so I did take a look and it was even easier to fix than I thought, just needed to replace InotifyWatcher with RecommendedWatcher at three points.

There's likely to be issues with how those notifications are handled/issued at the OS level due to differences between systems and I will take a look into that later, but it should at least compile and run now.

**Comment by berkus** [comment] 2019-04-11 13:13
Yeah, please do! *Jumping* wanna try it on macOS.

**Comment by rabite0** [comment] 2019-04-11 13:19
I already did, it's in the master branch. :) Just waiting for someone to report success before I close the issue.

**Comment by davidpdrsn** [comment] 2019-04-11 13:54
It isn't working for me. It builds successfully crashes on launch

![Screenshot 2019-04-11 at 15 54 09](https://user-images.githubusercontent.com/718941/55962917-159abb80-5c72-11e9-90a6-bfa14fb945f4.png)

I installed libmagic with `brew reinstall libmagic`. macOS 10.14.3, running in tmux.

**Comment by rabite0** [comment] 2019-04-11 14:38
From the looks of it, this is caused by the metadata-fetching, maybe related to the thread-pool somehow. Will investigate further, thanks for testing.

Closing this issue since this crash has nothing to do with file watching.

**Closed by rabite0** 2019-04-11 14:38 UTC
Labels: enhancement

**Comment by rabite0** [comment] 2019-04-13 14:09
See : #17 

Please test if it works.

**Comment by berkus** [comment] 2019-04-17 07:35
Cool, it builds, but crashes immediately on startup. Will open a new ticket.

**Comment by rabite0** [comment] 2019-04-17 10:22
It seemed to be fine from the reports I got, but apparently not. :(

If you care enough, please open a new one and include a stack trace if you can. It's probably rather an issue with a file it tries to load, rather than something that has to do with macOS. Since I added the panic-handler it should print it fine when it crashes.

You could try to open it in different directories and see if it starts up.

**Comment by berkus** [comment] 2019-05-06 16:16
Hi!
Not opening a new issue, because version `1.1.0` works fine on my mac! 🙇
